### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by ZXY12391** [biodog/dark_web_spider#2]
请问我已经把torrc的端口改为了我的梯子端口7890，没有改代码中的# 代理
proxy = {'http': 'socks5h:127.0.0.1:9050'}和改了代码中的proxy = {'http': 'socks5h:127.0.0.1:7890'}都报错了
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\pythonProject5\dark_web_spider\handle_login.py", line 44, in <module>
    get_chapter()
  File "C:\Users\admin\PycharmProjects\pythonProject5\dark_web_spider\handle_login.py", line 27, in get_chapter
    f.write(session.get(img_url).content)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\pythonProject5\venv\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\pythonProject5\venv\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\pythonProject5\venv\Lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\admin\PycharmProjects\pythonProject5\venv\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\admin\PycharmProjects\pythonProject5\venv\Lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

**Comment by biodog** [comment]
也许因为原先那个网址已经挂了
